repos:
  # default built-in pre-commit hooks
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  # sorting imports
  - repo: git@github.com:PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  # update python code to the "arg" version, use either --py38-plus or --py39-plus
  - repo: git@github.com:asottile/pyupgrade.git
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

  # remove unused imports
  - repo: git@github.com:PyCQA/autoflake.git
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ --in-place, --remove-all-unused-imports ]

  # python code formatter
  - repo: git@github.com:psf/black.git
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

    # linter with provided config, 7 is the fail threshold
  - repo: git@github.com:PyCQA/pylint.git
    rev: v2.12.2
    hooks:
      - id: pylint
        args: [ --rcfile=pylintrc, --fail-under=7 ]

    # commit message validation
  - repo: git@github.com:commitizen-tools/commitizen.git
    rev: v2.20.5
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
